### ISSUE TITLE
Schedule Scan Page not Found

### ISSUE THREAD

**Issue by S3ntago** [yogeshojha/rengine#982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

When I tried to set a schedule scan from `Targets` page `https://X.X.X.X/scan/default/schedule/target/2`, the application returning `Server Error (500)`.
![image](https://github.com/yogeshojha/rengine/assets/48615614/ee982f51-c081-4f61-b741-ee189fee34ec)

Also, same issue is happening when trying to access schedule scan from `Organization` page `https://X.X.X.X/scan/schedule/organization/1` same error is returning "Server Error (500)" 
![image](https://github.com/yogeshojha/rengine/assets/48615614/9b64d527-26d0-43f9-88fb-e82bab71cc5c)

I checked the code am not sure if there is something wrong with the slug related to the "Schedule Scan" or now as per the below screenshot:

Below screenshot from the following file: `/usr/src/app/targetApp/templates/target/list.html`

![image](https://github.com/yogeshojha/rengine/assets/48615614/996df4c9-2f94-4e12-a1c4-c014ace0f465)

### Expected Behavior

Access to the Schedule Scan page

### Steps To Reproduce

Access `https://X.X.X.X/scan/default/schedule/target/2` from `Targets` page
Access `https://X.X.X.X/scan/schedule/organization/1` from `Organization` page

### Environment

```markdown
- reNgine: 2.0
- OS: Ubuntu
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser: Chrome
```

**Comment by S3ntago** [comment]
@psyray this didn't fix the issue, I added `DJANGO_CELERY_BEAT_TZ_AWARE = False` settings to the `web/reNgine/settings.py` and `docker-compose start celery-beat` but the issue is not solved as shown below:
![image](https://github.com/yogeshojha/rengine/assets/48615614/a81b23be-01cf-49be-a06f-8badfea4c2ee)
![image](https://github.com/yogeshojha/rengine/assets/48615614/03a83e9a-02a8-4951-bb24-6c61a415b952)
![image](https://github.com/yogeshojha/rengine/assets/48615614/c7f49151-f4a1-4831-a762-baa025ab38e9)

**Comment by psyray** [comment]
> @psyray this didn't fix the issue, I added `DJANGO_CELERY_BEAT_TZ_AWARE = False` settings to the `web/reNgine/settings.py` and `docker-compose start celery-beat` but the issue is not solved as shown below: ![image](https://user-images.githubusercontent.com/48615614/275595939-a81b23be-01cf-49be-a06f-8badfea4c2ee.png) ![image](https://user-images.githubusercontent.com/48615614/275596107-03a83e9a-02a8-4951-bb24-6c61a415b952.png) ![image](https://user-images.githubusercontent.com/48615614/275596721-c7f49151-f4a1-4831-a762-baa025ab38e9.png)

Could you try a `docker container ls` and post output

**Comment by S3ntago** [comment]
> > @psyray this didn't fix the issue, I added `DJANGO_CELERY_BEAT_TZ_AWARE = False` settings to the `web/reNgine/settings.py` and `docker-compose start celery-beat` but the issue is not solved as shown below:
> 
> Could you try a `docker container ls` and post output

![image](https://github.com/yogeshojha/rengine/assets/48615614/ea8b41eb-4b74-4205-86f6-c514deba2d07)

**Comment by S3ntago** [comment]
@psyray Also, someone on Discord suggested that this issue because a slug for Schedule scan is missing from the code:
![image](https://github.com/yogeshojha/rengine/assets/48615614/2cb70e25-f0cb-4ad1-ad87-eaf78e325fff)
![image](https://github.com/yogeshojha/rengine/assets/48615614/bbf4004e-f390-4cdd-b598-e44f1eeb5e2a)

**Comment by psyray** [comment]
> @psyray Also, someone on Discord suggested that this issue because a slug for Schedule scan is missing from the code: 

ok, did you try ?

**Comment by S3ntago** [comment]
> > @psyray Also, someone on Discord suggested that this issue because a slug for Schedule scan is missing from the code:
> 
> ok, did you try ?

I don't know what is the correct slug and how it should be, appreciate your help if you can.

**Comment by psyray** [comment]
> > > @psyray Also, someone on Discord suggested that this issue because a slug for Schedule scan is missing from the code:
> > 
> > 
> > ok, did you try ?
> 
> I don't know what is the correct slug and how it should be, appreciate your help if you can.

Maybe you should ask directly at harjulianto on the discord
Then if it works for you you can post solution here :wink:

**Comment by S3ntago** [comment]
> > > > @psyray Also, someone on Discord suggested that this issue because a slug for Schedule scan is missing from the code:
> > > 
> > > 
> > > ok, did you try ?
> > 
> > 
> > I don't know what is the correct slug and how it should be, appreciate your help if you can.
> 
> Maybe you should ask directly at harjulianto on the discord Then if it works for you you can post solution here 😉

I did already asked him and waiting his response, at the meantime I opened this issue here in case if anyone has the same issue or if anyone already know a solution.

So is schedule scan works fine with you ?

**Comment by psyray** [comment]
> I did already asked him and waiting his response, at the meantime I opened this issue here in case if anyone has the same issue or if anyone already know a solution.
> 
> So is schedule scan works fine with you ?

Nope, same as you, but i'm not using it so it's not my priority to investigate more at this time

**Comment by psyray** [comment]
@S3ntago Fixed in #996 
Apply modifications to your instance and page should displayed
I don't have tested the schedule scan functionality, I've only fixed the page display

**Comment by podeappa** [comment]
This fixed the schedule page for target but for organization I am still getting 500

**Comment by NadgobKhan** [comment]
> This fixed the schedule page for target but for organization I am still getting 500

I am as well, but the scheduled scan is saved and can be seen in the "Scheduled Scans" tab (even though the scan doesn't actually start, check https://github.com/yogeshojha/rengine/issues/1015#issuecomment-1926731766 )
